#!/bin/bash
echo "Check adding values, getall and getp..."
MYDIR=$(dirname $0)
set -o pipefail
{
    $MYDIR/../examples/main << EOF
9 3 3 4 5 4.9 8 3.3 2 0.1
EOF
} | tee /dev/stderr | awk -f $MYDIR/helper00.awk
