#!/bin/bash
echo "Check adding values, getall and getp with different timestamps (lasting ~90s)..."
MYDIR=$(dirname $0)
set -o pipefail
{
    for i in 9 3 3 4 5 4.9 8 3.3 2 0.1; do
        sleep 9
        echo $i
    done
} | $MYDIR/../examples/main | tee /dev/stderr | awk -f $MYDIR/helper02.awk
